### PR TITLE
Fixed wrong translation keys [2.5.1 Update]

### PR DESCRIPTION
**Pull request by TheblueJo**
These translation keys were outdated thereby showing the translation key instead of it's name in-game.

### CODE REVIEW

**Comment by smell-of-curry** [comment]
can you fix this with the new update

**Comment by TheblueJo** [comment]
Some Pokemons still have a "-" in their names (not the keys; german and english). If you want them gone just tell me.

**Comment by smell-of-curry** [comment]
Yeah can you remove them

**Comment by smell-of-curry** [comment]
hey for up grade, `up-grade` should be removed and `up_grade` should be there, I guess I forgot to check when I was fixing that item.

**Pull request merged**
