### PR TITLE
Langs german + spanish 2.10.7, done

### PR DESCRIPTION
**Pull request by TheblueJo**
There were 5000+ additions, so it'll take a few days or weeks until I've completed german and spanish translations.
Currently (only german):
- Move phrases during battle
- Battle ui menu langs
Not yet:
- Move names + descriptions
- TMs
- spanish

### CODE REVIEW

**Comment by smell-of-curry** [comment]
Yeah I Know, hahah it's going to be a lot. now that the entire addon is translatable.

**Comment by TheblueJo** [comment]
There are some berries from J to L that aren't there (?):
Hopo Berry, Jaboca Berry, Kasib Berry, Kebia Berry, Kee Berry, Kelpsy Berry, Lansat Berry.

**Comment by smell-of-curry** [comment]
Oh shoot, well I used the ones pixelmon had. I guess there missing some

**Comment by smell-of-curry** [comment]
Never mind, we are only missing Hopo Berry

**Comment by smell-of-curry** [comment]
Let me know when this is done

**Comment by TheblueJo** [comment]
The last 3 abilities are not official
Some abilities that aren't listed / implemented which I found are: Mind's Eye, Poison Puppeteer, Supersweet Syrup, Tera Shell, Tera Shift, Teraform Zero, Toxic Chain, Hospitality and Embody Aspect

**Comment by Idkthisisfordahaxks** [comment]
Im confused with the final 2 steps to get the beh pack

**Comment by smell-of-curry** [comment]
Final 2 steps?

**Comment by smell-of-curry** [comment]
hows it going?

**Comment by TheblueJo** [comment]
The TMs, Ability descriptions, Moves, Move descriptions, battle item descriptions, and some Spanish battle UI texts are left

**Comment by smell-of-curry** [comment]
hows this?

**Comment by TheblueJo** [comment]
Also a little suggestion: can we add or remove the _ underscore from/to item names, so the item in the showdown.item.x and item.x have the same x? Currently they're
- showdown.items._blackbelt_.name=Black Belt, and
- item.pokeb:_black_belt_=Black Belt
having blackbelt as x for as an example

**Comment by Personal0ne** [comment]
I suggest using this tool [Any Language MCBE Lang auto translater] (https://solveddev.github.io/AnyLanguage). I used it to make the process of converting LANG files much easier, and I only had to proofread them to convert them into my native language.

i hope that help you.

**Comment by smell-of-curry** [comment]
> Also a little suggestion: can we add or remove the _ underscore from/to item names, so the item in the showdown.item.x and item.x have the same x? Currently they're
> 
> * showdown.items._blackbelt_.name=Black Belt, and
> * item.pokeb:_black_belt_=Black Belt
>   having blackbelt as x for as an example

Some of those need changing, but the thing about it is, is that those names are from pokemon showdown, the other ones are from our addon. Showdown doesn't use `_` and we do.

**Comment by TheblueJo** [comment]
Still to be done:
- ability descs
- moves + in TMs
- move descs
Finally seeing the light at the end of the tunel

**Comment by TheblueJo** [comment]
This will be finished by sunday, I think

**Comment by TheblueJo** [comment]
Done

**Pull request merged**
