### PR TITLE
Updated pt-BR LANG - fixed battle side texts and others server messages [Still under review]

### PR DESCRIPTION
**Pull request by Personal0ne**
-Fixed messages parsing
-added translations for moves descriptions and many others.
-keeped moves names by now

**I'm open to feedback from Brazilian Portuguese speakers and others**

### CODE REVIEW

**Comment by Personal0ne** [comment]
i'm reviewing all the changes for now

**Comment by smell-of-curry** [comment]
is this done?

**Comment by Personal0ne** [comment]
> is this done?

not yet

**Comment by Personal0ne** [comment]
i found more problems, then i will find other ways to solve these problems, for now i'll close this pull request draft

**Pull request closed without merging**
